version: '3'

services:
  web:
    image: gcr.io/siiid-prd/siiid-frontend:latest
    ports:
      - "3341:3000"
  api:
    image: gcr.io/siiid-prd/siiid-backend-sv:latest
    environment:
      - OWM_API_KEY=CiQAu/EDeTIx+WRDX5gdvJSbZYQ1nlIob/UCl5J1p5CAmR90RJYSSgBldElcTDnBeR564YayzZeGqVSdi/n4sQeu7vv9WFCUZi6HcV0726S9prnA9zCtdQfALyREiITYuj7P9HjV97NWCz+vq9KvoZJi
      - PLACE_API_KEY=CiQAu/EDeU4v9M80Af2Q9EaeZOgD5qDG4m1oDUHMrG/Sx7cNvroSUABldElcfgjmBvEqHnlqynqwtI3CPkg/L4Z3R60Sl0jA37H+jTyr9YIMaoPmuZxSL+sP1jdOIVlBptRJmBQH9Npry6wP7yLWGTkoljcnMW2N
      - GOOGLE_APPLICATION_CREDENTIALS=/var/secret/siiid-developer.json
    volumes:
      - "./secret:/var/secret"
    links:
      - api-gateway
      - redis-master
      - redis-slave
  api-gateway:
    image: gcr.io/siiid-prd/siiid-backend-gk:latest
    ports:
      - "8765:8080"
    environment:
      - SERVER_NAME=api
      - SERVER_PORT=5001
  redis-master:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - "./data/reis:/data"
  redis-slave:
    image: redis
    command: redis-server --slaveof redis-master 6379
    ports:
      - "6381:6379"
    volumes:
      - "./data/reis:/data"
